### ISSUE TITLE
jeep-sqlite - want to ensure initialized before app is mounted

### ISSUE THREAD

**Issue by mjgoeke** [jepiqueau/jeep-sqlite#1]
Hi - I'm using the @capacitor-community/sqlite plugin, for use in electron and iOS, and I'm beginning to plug in jeep-sqlite for more rapid development of my web app (vue 3.x).

In the non jeep-sqlite version I like how it's working.  I ensure the database connection is created, opened, and the required tables are created, before moving on to creating and mounting the app.
It's valuable to have a guaranteed-initialized database by the time my app starts, it removes the need for await/promises just to access the sqlite db object.

Since jeep-sqlite is a web component, I'm having trouble keeping the database initialization in my main.ts, but have had to defer it into my App.vue `mounted` lifecycle hook.  But I'm fighting with timing issues, as nested view's `mounted` events have code that tries to access the db, but the database is not initialized yet.

My question is, how should I go about ensuring jeep-sqlite is initialized earlier in my app's startup?
(perhaps there's a way to initialize jeep-sqlite without needing the custom element rendered in the dom)

Let me know if you want code examples of what I have.
Thank you for your help!

**Comment by jepiqueau** [comment]
@mjgoeke thanks for using the plug-in. Did you look at vue-sqlite-app and vue-sqlite-app-starter You cannot do what you said "initializing jeep-sqlite without needing the custom element rendered in the Dom ". You have to transfer the initialization of the database in App.Vue. you can share your code if it is still required after having look at the vue-sqlite-app-starter. I will not work on it today but may be over the weekend

**Comment by jepiqueau** [comment]
@mjgoeke your App.Vue could be
```
<template>
  <ion-app>
    <template v-if="platform === 'web'">
      <jeep-sqlite />
    </template>
    <ion-router-outlet />
  </ion-app>
</template>

<script lang="ts">
import { IonApp, IonRouterOutlet } from '@ionic/vue';
import { defineComponent, getCurrentInstance, onMounted} from 'vue';
import { useSQLite} from 'vue-sqlite-hook/dist';
import { Capacitor } from '@capacitor/core';
export default defineComponent({
  name: 'App',
  components: {
    IonApp,
    IonRouterOutlet,
  },
  setup() {
    const platform = Capacitor.getPlatform();
    const app = getCurrentInstance();
    const isModalOpen = app?.appContext.config.globalProperties.$isModalOpen;
    const contentMessage = app?.appContext.config.globalProperties.$messageContent;
    const jsonListeners = app?.appContext.config.globalProperties.$isJsonListeners;
    onMounted(async () => {
      console.log(' in App on Mounted')
      const ionAppEl = document.querySelector('ion-app');
      if(ionAppEl != null) {
        console.log(`ionAppEl ${JSON.stringify(ionAppEl)}`);
      } else {
        console.log(' ionAppEl is null');
      }
      const onProgressImport = async (progress: string) => {
        if(jsonListeners.jsonListeners.value) {
          if(!isModalOpen.isModal.value) isModalOpen.setIsModal(true);
          contentMessage.setMessage(
              contentMessage.message.value.concat(`${progress}\n`));
        }
      }
      const onProgressExport = async (progress: string) => {
        if(jsonListeners.jsonListeners.value) {
          if(!isModalOpen.isModal.value) isModalOpen.setIsModal(true);
          contentMessage.setMessage(
            contentMessage.message.value.concat(`${progress}\n`));
        }
      }
      if( app != null) {  
        app.appContext.config.globalProperties.$sqlite = useSQLite({
          onProgressImport,
          onProgressExport
        });
        if(platform === "web") {
          await customElements.whenDefined('jeep-sqlite');
          const jeepSqliteEl = document.querySelector('jeep-sqlite');
          if(jeepSqliteEl != null) {
            console.log(`$$ jeepSqliteEl ${JSON.stringify(jeepSqliteEl)}`);
          } else {
            console.log('$$ jeepSqliteEl is null');
          }
        }
          console.log('after useSQLite')
      }
    });
    return {platform}
  }
});
</script>
```

**Comment by saadsidqui** [comment]
Hello @jepiqueau !
Let me preface this with a thank you for your work on the capacitor SQLite plugin, the Vue Hook for it, and this. It's really great work !

I'm currently in the same spot as OP where I would really like to initiate this component before the Vue instance is created, which is not possible currently due to this relying on the rendered DOM to provide the element on which the functionality is pegged.

I'm not sure why we actually need a DOM element at all (unless I'm missing something).
In an ideal world, the core functionality could be extracted into a module. This, in an Ionic app for example, would allow a check for the platform in userland and the proper handler could be substituted _(i.e. this for web and the vue hook for other platforms)_.

Something like:
![image](https://user-images.githubusercontent.com/25284407/133026328-a1de81c0-db4e-46a1-acbe-204239af8bc8.png)
*(`service.instance`, in this case, is just a variable used to implement a quick and dirty singleton. It's incidental and could be any other regular variable)*.

I'm not very familiar with Stencil, so apologies if I'm saying non-sense here.

**Comment by jepiqueau** [comment]
@sidquisaad thanks for using the capacitor-community/sqlite plugin and thanks for your comment. This should be an issue in the plug-in not here. Having said that it should be in the DOM as it is where the plug-in will look at to decide if there is a Web implementation or not. This has been done to help the developers to develop and test an app in the browser before to test it as native application iOS, Android or Desktop app Electron. It is mentioned at the time you create your native builds to remove the jeep-sqlite component and the sqlite.connection. js wasm file from the app folder to not pay the cost (package size) and this is the reason why I use and develop a Stencil component companion which can be there or not. Hope the reasons are clear now  for you. This force to move the definition from main.ts to App.vue

**Comment by mjgoeke** [comment]
Thank you for your prompt feedback!
I really appreciate the high quality work you're doing both here and in the capacitor community sqlite plugin :-)

I'm planning to use the web implementation throughout development, it provides more rapid iteration to build/hot reload a web app than (doing all that) plus building the electron or iOS version on top.
My time is split so it may be a couple weeks before I'm focused on the sqlite part of my app again.  If I find an approach that works for me I'll post it here. (or edit this comment to include it).

**Comment by jepiqueau** [comment]
@mjgoeke ok if you find a better approach feel free to share it I will appreciate

**Comment by jepiqueau** [comment]
@mjgoeke i will close the issue, feel free to re-open it when you will be focusing on the sqlite part of your app, if it is required. Good development

**Comment by mjgoeke** [comment]
Thanks I'm starting to look at this again.
I think I can describe better where I'm getting hung up now.

My SPA looks kinda like this

```
main (initialization goes here, including db connection)
App
    (these views use the db in their 'created' hook)
    Login
    feature1/SomeScreen1
    feature1/SomeScreen2
    etc.
```
this was all working.

When I pull in jeep-sqlite, I don't have access to the db in `created` anymore, I have to move all loading to `mounted` to guarantee persistence (via jeep-sqlite) is available.  This slows rendering of the pages quite a bit (the dom has to be fully loaded before we load the data for the view, and then it rearranges the dom again).
Finally, I want to ensure the db is initialized in only one place, so I would naturally put it in something like App, in mounted.
Unfortunately this wasn't working either because of the order each view's mount is invoked, App.mounted gets invoked last, after e.g. Login.mounted.

If I have `App`, with a router, so it loads a subview of `Login`, and `Login` attempts to load current credential information, I would like it in `created`, failing that at least in `mounted`.  But I've place my db initialization in `App.mounted`.
`App.mounted` is called last - after all sub views `mounted` have completed. :-(

This is what I'm stuck on.  I can't figure out how to ensure the persistence is available in each view without every single view being responsible to initialize the db connection, and I'm not sure what this would even look like.  Hopefully not a jeep-sqlite html5 component in every view.

I'll check the example apps again and see how this was managed, but I'm concerned the app starters were 'toy' applications, where establishing a shared db connection for the entire SPA wasn't a thing.  There are just little islands of db connectivity isolated within individual views, where tests are then run, and entire connection lifecycle is managed within the view, and it happens on a button press, not in `created` or `mounted` hooks.

I'm picking up work on this again and will comment if I find a clean solution.
Ideally though I'd be able to initialize my db connection (and e.g. run code to ensure my schema is created) during app initialization instead of needing to wait for the first render of the dom.
Perhaps jeep-sqlite could be ported to _not_ be wrapped up as a Stencil component?  If necessary, is this something I could help make happen?

**Comment by jepiqueau** [comment]
@mjgoeke As already mentioned, the Stencil component `jeep-sqlite` has been developed to easily test your app with the Browser and the remove it when you go native to decrease the package size of the native apps. That were the comments from developers when i start implementing it directly in the plugin. The demonstrating vue apps show how to define it in the App and there is nothing against that you can define your database schema in the App and later to fill the data in the individual views. I will have a look on this 
```
I would like it in created, failing that at least in mounted. But I've place my db initialization in App.mounted.
App.mounted is called last - after all sub views mounted have completed. :-(
```

**Comment by jepiqueau** [comment]
@mjgoeke i fixed you issue see example `https://github.com/jepiqueau/vue-sqlite-app-test.git` this should answer all your queries hopefully. i will update all the vue apps example to fit with that one when you will have tell me that it works on your side

**Comment by mjgoeke** [comment]
### Bravo, thank you.
I will try this on Monday when I'm back to the project.

---------
I'm rather new to web dev, and mainly have experience with vue.
I'll reiterate your supplied solution for others here:

I was looking to initialize the jeep-sqlite component in my App.vue component.  But this was too late in the lifecycle.
Your solution is in main.ts, it attaches to the `DOMContentLoaded` event on the `window` object.  This fires before even the vue framework is initialized/mounted.
It conditionally (`Capacitor.getPlatform() === 'web'`) inserts the 'jeep-sqlite' element on the page, and initializes jeep-sqlite (in this case using `vue-sqlite-hook`).
I personally will hook it up myself (not using `vue-sqlite-hook`), and instead of assigning (vue's) app.config.globalProperties.$db will be assigning a simple singleton service and use that everywhere it's needed.  (I have contexts outside of the view/viewmodel where I need persistence).

I was worried about a race condition between the db initialization and the vue framework spinning up, but I see line 81 is where `app.mount()` gets hooked up to run. The db initialization would be awaited, so it looks like there's no possibility of a race condition :-)

For people needing a push in the right direction, here's the code example jepiqueau sent me, specifically the lines I mentioned above:
https://github.com/jepiqueau/vue-sqlite-app-test/blob/0641b97fdce7a278e98efb4b25aaa4808d032d3c/src/main.ts#L35

and here's the relevant code block copied here for convenience:

``` typescript
window.addEventListener('DOMContentLoaded', async () => {
  const platform = Capacitor.getPlatform();

  const app = createApp(App)
    .use(IonicVue)
    .use(router);

  if(platform === "web") {
		const jeepSqlite = document.createElement('jeep-sqlite');
		document.body.appendChild(jeepSqlite);
    await customElements.whenDefined('jeep-sqlite');
  }
  app.config.globalProperties.$sqlite = useSQLite();
  const sqlite = app.config.globalProperties.$sqlite;
  try {
    if(platform === "web") {
      await sqlite.initWebStore();
    }
    await sqlite.checkConnectionsConsistency({
      dbNames: [], // i.e. "i expect no connections to be open"
    })
    const db: SQLiteDBConnection = await sqlite.createConnection("test_vue");
    console.log("> createConnection  'test_vue' successful\n");
    //mjgoeke comment: I snipped code and added my Database.initialize here.  Use link above to see full original source.
    await Database.initialize(db); //set my singleton and ensure schema initialized
  } catch (err) {
    console.log(`App Error: ${err}`);
  }
  router.isReady().then(() => {
    app.mount('#app');
  });
});
```
