### ISSUE TITLE
Jeep Crashes on livereload with devtools open in Chrome

### ISSUE THREAD

**Issue by Dante1349** [jepiqueau/jeep-sqlite#10]
Hey,

I'm using @capacitor-community/sqlite and since some days when i use ionic serve, jeep crashed with the exeption:

`Unhandled Promise rejection: No available storage method found. ; Zone: <root> ; Task: Promise.then ; Value: Error: No available storage method found`

which seems to be a localForage issue:

https://github.com/localForage/localForage/issues/722

but when i close the dev tools and reload again, everything works fine.

My chrome version is: Version 102.0.5005.61 (Official Build) (64-bit)

I also tried updating all dependencies: 
"@capacitor-community/sqlite": "^3.5.1-1",
"jeep-sqlite": "^1.5.2",
"sql.js": "^1.6.2",

I know this is really strange, but it is also frustrating. I hope you can help me with that.

Since this is more related to jeep-sqlite than to @capacitor-community/sqlite i posted the issue here.

**Comment by jepiqueau** [comment]
@Dante1349 can you show me how you did implement the jeep-sqlite in your code.

**Comment by jepiqueau** [comment]
@Dante1349 to have the component working with livereload you need to check for connection consistency

**Comment by jepiqueau** [comment]
@Dante1349 use checkConnectionsConsistency method before opening a connection there are some examples of this in the different app starters

**Comment by Dante1349** [comment]
@jepiqueau Thank you for your quick response! The problem is, that we're already doing this. And we used the same code before, this issue seems to be new somehow, but i cannot really say what happens here. 

This is the code how we connect: 
```    
        if ((await this.sqliteService.isConnection(dbName)).result) {
            this.db = await this.sqliteService.retrieveConnection(dbName);
        } else {
            const openedConnections = (await this.sqliteService.checkConnectionsConsistency()).result;
            if (openedConnections) {
                console.log("Open db conns cleared")
            }
            this.db = await this.sqliteService.createConnection(dbName, true, "secret", 1);
        }

        await this.db.open();
```

**Comment by jepiqueau** [comment]
@Dante1349 you should do the checkConnectionsConsistency first and then the isConnection 
If both return true do the retrieveConnection otherwise createConnection

**Comment by Dante1349** [comment]
@jepiqueau ok i adjusted it accordingly but i still have the same issue, this is the new code 
```
        const consistencyCheckResult: boolean | undefined = (await this.sqliteService.checkConnectionsConsistency()).result
        const consistencyCheck: boolean = consistencyCheckResult || false;
        const isConnectionResult: boolean | undefined = (await this.sqliteService.isConnection(dbName)).result
        const isConnection: boolean = isConnectionResult || false

        if (consistencyCheck && isConnection) {
            console.log("Existing Database connection retrieved.");
            this.db = await this.sqliteService.retrieveConnection(dbName);
        } else {
            console.log("No existing Database connection retrieved.");
            this.db = await this.sqliteService.createConnection(dbName, true, "secret", 1);
        }

        await this.db.open();
        console.log("Database opened");
```
But unfortunately its still the same result

**Comment by Dante1349** [comment]
@jepiqueau We somehow managed to fix the issue again. It had something to do with the local node_module versions i think we can close the issue. I will come back in case this occurs again. But thank you for your help.

**Comment by jepiqueau** [comment]
@Dante1349 happy that you fix it as i could not reproduce it. Do not hesitate to come back when required.
