### ISSUE TITLE
Sponsoring for continued work?

### ISSUE THREAD

**Issue by muuvmuuv** [jepiqueau/jeep-sqlite#16]
Are there options to sponsor you and your effort in SQLite for Capacitor?

**Comment by jepiqueau** [comment]
@muuvmuuv i work on my free time to develop this and i am a retired person since 2015. 
Do you see features that are missing for your own development which can also be useful for others

**Comment by muuvmuuv** [comment]
Oh, didn't know, great that this works for you!

We are fine with all features that are included. 

We are just looking to sponsor some people for their work on libs that we use and are currently creating a list of potential projects.

**Comment by jepiqueau** [comment]
@muuvmuuv what type of sponsoring are you looking at ? What will be my contribution and obligations?

**Comment by muuvmuuv** [comment]
Like other authors do through GitHub Sponsoring

**Comment by jepiqueau** [comment]
@muuvmuuv i will have a look and come back to you

**Comment by jepiqueau** [comment]
@muuvmuuv following your advice, i created a GITHUB Sponsors profile
[GITHUB Sponsors profile](https://github.com/sponsors/jepiqueau?preview=true)

**Comment by muuvmuuv** [comment]
Great! I will add it to our list for possible donations :)
