### ISSUE TITLE
AutoSave breaks transactions

### ISSUE THREAD

**Issue by bokolob** [jepiqueau/jeep-sqlite#17]
If autosave is enabled then commits and rollbacks produces error - "Execute: ExecuteSQL: ExecuteSQL: Execute: cannot commit - no transaction is active"

**Comment by jepiqueau** [comment]
@bokolob can you provide an example

**Comment by marcelarmz** [comment]
Hi @jepiqueau, I have the same problem. I created an example with your ionic-sqlite-typeorm-app, you can view the fork [here](https://github.com/marcelarmz/ionic-sqlite-typeorm-app/tree/jeep-sqlite-autosave). 

For some reason that I still don't understand, the "no transaction is active" error only appears in the first two refreshes of my example, but at all times I noticed that even if I manually declare `<jeep-sqlite autoSave="true">` in the html, in DevTool I can see it changes to` <jeep-sqlite autosave>` (all chars in lowercase, and the "true" value getting removed).

Hope this example helps. Thank you.

**Comment by jepiqueau** [comment]
@marcelarmz thanks for this. I will have a look on my free time and revert to you

**Comment by jepiqueau** [comment]
@marcelarmz @bokolob This has been fixed i release 1.7.1

**Comment by jepiqueau** [comment]
@marcelarmz By the way you do not need to change all the code of `ionic-sqlite-typeorm-app` like you did you can do this in the `main.ts` to set the `autosave` property
```
  window.addEventListener('DOMContentLoaded', async () => {
      const jeepEl = document.createElement("jeep-sqlite");
      document.body.appendChild(jeepEl);
      jeepEl.autoSave = true;
  });
```

**Comment by jepiqueau** [comment]
@marcelarmz release 2.0.0 is out using @stencil/core@3.0.0

**Comment by marcelarmz** [comment]
I tested the new version and your suggestion and works perfectly. Thank you!!
