### ISSUE TITLE
Upgrade statements execute in wrong order

### ISSUE THREAD

**Issue by dmx-patrick** [jepiqueau/jeep-sqlite#18]
If your database version is higher than 9 the upgrade statements are executed in the incorrect order. JavaScript sorts arrays comparing values as strings, so `[1,2,10].sort()` returns `[1,10,2]`.

The problem code:
https://github.com/jepiqueau/jeep-sqlite/blob/a05d8e5944144c5f6f01f7be9e9fe7583c738e36/src/utils/utils-upgrade.ts#L12-L14

**Comment by jepiqueau** [comment]
@dmx-patrick fix in 1.6.8 Can you close the issue after test in your side

**Comment by dmx-patrick** [comment]
Works correctly now, thx.
