### ISSUE TITLE
Restore database doesn't work when upgrade fails

### ISSUE THREAD

**Issue by dmx-patrick** [jepiqueau/jeep-sqlite#19]
When something goes wrong with the upgrade it should restore the backup database. The database name is prefixed twice causing the restore action to fail.

Restore method called with full database name including the prefix, second argument should only be the prefix.
https://github.com/jepiqueau/jeep-sqlite/blob/a05d8e5944144c5f6f01f7be9e9fe7583c738e36/src/utils/database.ts#L82

https://github.com/jepiqueau/jeep-sqlite/blob/a05d8e5944144c5f6f01f7be9e9fe7583c738e36/src/utils/utils-store.ts#L60-L61

**Comment by jepiqueau** [comment]
@dmx-patrick fix in 1.6.8

**Comment by dmx-patrick** [comment]
fixed
