### ISSUE TITLE
Is there any way to read an existing database from the developer tab in the browser?

### ISSUE THREAD

**Issue by CosminCraciun** [jepiqueau/jeep-sqlite#2]
Hei!

Great work with this package!

I was wondering if there is any 'user-friendly' way to read the stored database from the developer tab in the browser.
Or maybe downloading the database and querying directly somehow.

Thanks!

**Comment by jepiqueau** [comment]
@CosminCraciun Thanks for using the component. If you can read your database from the developer tab make a small development to read it and convert it in the JsonSQLite object and after having check the validity with isJsonValid method use the importFromJson method to create the database. Hope this will be helpful

**Comment by jepiqueau** [comment]
@CosminCraciun Did you progress on this?

**Comment by CosminCraciun** [comment]
Yes, I am able to read it like that. Thank you.

**Comment by jepiqueau** [comment]
@CosminCraciun I am glad that it is workin.  Have a good development
