### ISSUE TITLE
Waiting until table is loaded

### ISSUE THREAD

**Issue by bokolob** [jepiqueau/jeep-sqlite#23]
Hello!
What is the right way to wait until saved data is loaded ? It seems that in chrome it is loaded just after open call finishes, on safari and firefox there is some delay

**Comment by pkzOR** [comment]
Interested in this too

**Comment by jepiqueau** [comment]
@bokolob Are you calling the open without an await ? Can you show me the code

**Comment by jepiqueau** [comment]
@bokolob @pkzOR Is the database large?

**Comment by jepiqueau** [comment]
@bokolob @pkzOR Any news on this Still waiting your example to reproduce it

**Comment by jepiqueau** [comment]
@bokolob @pkzOR As you do not follow-up , i assume the issue has fixed. So i close it
