### ISSUE TITLE
Is there a possibility to query the database in Browser?

### ISSUE THREAD

**Issue by hhimanshu** [jepiqueau/jeep-sqlite#25]
Hello @jepiqueau , 
I am using this library and it works well. I can see the db in my `Application` as below
<img width="1100" alt="image" src="https://github.com/jepiqueau/jeep-sqlite/assets/6589036/1478019b-4de9-4b0f-8b55-d252d099d920">

What I am wondering is if there is a way to connect to this database and run queries. Something similar to `sqlite3 <path to store in browser>`

This is because all the changes are happening here and I want to be able to quickly analyze the data.

Do you happen to know any approaches that can help?

Thank you

**Comment by jepiqueau** [comment]
@hhimanshu for sure you can. Look at the different html files in the jeep-sqlite folder you can clone it do a npm install and do a npm start to run the différents examples

**Comment by hhimanshu** [comment]
Thank you, @jepiqueau, this has helped me a lot. I would summarize my steps here. Maybe, this helps others as well

### Querying the database in browser console
- Run the following steps in console
```js
const jeepSqlite = document.querySelector('jeep-sqlite');
await jeepSqlite.createConnection({
  database:"myDb",
  version: 1
});
await jeepSqlite.open({database: "myDb"});
const isDB = await jeepSqlite.isDBOpen({database: "myDb"})
isDB // returns {result: true}
```

At this time, you are connected to SQLite database in your browser. You can execute queries as belo

```js
await jeepSqlite.query({database: "myDb", statement: 'SELECT * from myTable1;'})
await jeepSqlite.query({database: "myDb", statement: 'SELECT * from myTable2;'})
await jeepSqlite.query({database: "myDb", statement: 'SELECT * from myTable3;'})
```
