### ISSUE TITLE
Bug: Reset isTransactionActive without autosave

### ISSUE THREAD

**Issue by paulstelzer** [jepiqueau/jeep-sqlite#26]
I am using the app without autosave. If an error occurs, the whole app is not working anymore because isTransactionActive will not be resetted in executeSet

https://github.com/jepiqueau/jeep-sqlite/blob/e36d81dfd4fcdf6556a79cc646f05f894794c4cb/src/utils/database.ts#L292-L295

It should be equal to executeSql. here this flag will be set to false outside of the autoSave clause

https://github.com/jepiqueau/jeep-sqlite/blob/e36d81dfd4fcdf6556a79cc646f05f894794c4cb/src/utils/database.ts#L244-L246

**Comment by jepiqueau** [comment]
@paulstelzer Thanks for this. Fixed in 2.3.7 . Please close the issue after test

**Comment by paulstelzer** [comment]
@jepiqueau Thank you, everything is working again
