### ISSUE TITLE
copyFromAssets relative path causing issues

### ISSUE THREAD

**Issue by rain2o** [jepiqueau/jeep-sqlite#29]
I noticed an issue while working with this lib. If loading my app in a nested path, the `copyFromAssets` command, which runs when the app loads, is failing. It looks like it's trying to load the JSON file from a relative path.

https://github.com/jepiqueau/jeep-sqlite/blob/a7566249cddabddb737281fe0ed4f6c3f7e168e8/src/components/jeep-sqlite/jeep-sqlite.tsx#L1518

I also found #12 which seems like it had the same issue in a different location. I'm guessing doing the same, prefixing the path with `/`, would resolve this issue.

**Comment by jepiqueau** [comment]
@rain2o What do you mean by  'If loading my app in a nested path' did you test it by adding a '/' in front

**Comment by jepiqueau** [comment]
@rain2o this is fixed in 2.5.4
