### ISSUE TITLE
How to view/query/export the sqlite db in the browser

### ISSUE THREAD

**Issue by mjgoeke** [jepiqueau/jeep-sqlite#3]
We're using the @capacitor-community/sqlite plugin, and we're using jeep-sqlite in the browser.
We're mainly developing in the browser to allow us to iterate faster, instead of waiting for electron or iOS to finish building each time we have a change.

JeepSqlite is working, and I see 'jeepSqliteStore' in Chrome's Application/IndexedDB section.
The visualization tools only take me that far though.  I can see my application's db in the key-value pairs, but the value is just an Uint8Array().

What is a good way to...
1) view the data?
2) export the data?

If I could export, I could use separate tools to view the data.
Or perhaps there's a chrome plugin to unwrap the sqlite data in localforage and query it?
Is there a common practice people use to view or export their data in this format?

It's very valuable for us to be able to see the data as we're developing.
Thank you!

**Comment by mjgoeke** [comment]
I found a solution for exporting - I was mainly struggling with the right methods to output the stream to file.  It kept being corrupted, but I had no idea if what I was trying would work at all.

This StackOverflow answer ended up helping: https://stackoverflow.com/questions/25354313/saving-a-uint8array-to-a-binary-file

I had been using things like `new TextDecoder().decode(data))`, `encodeURIComponent(data)`. In the end, the working implementation looks like this:

``` typescript
  async ExportDb(): Promise<void> {
    if (Capacitor.getPlatform() !== 'web') return;
    await this.flush();
    const db = localForage.createInstance({ name: 'jeepSqliteStore', storeName: 'databases' });
    const data = await db.getItem<Uint8Array>(this.dbFilename);
    if (!data) return;

    this.initiateDownload(this.dbFilename, 'application/vnd.sqlite3', data); //'application/octet-stream' works fine too
  }

  private initiateDownload(filename: string, dataType: string, data: BlobPart) {
    const blob = new Blob([data], { type: dataType });
    const a = document.createElement('a');
    a.href = window.URL.createObjectURL(blob);
    a.download = filename;
    a.click();
  }
```

If I'm doing it "the hard way" I'd love to know an easier way.  Otherwise, consider this closed.
Thanks for jeep-sqlite!


edit:
It occurs to me I don’t need the DB most of the time, I just need to query it to check data.
Making a helper method available (in dev mode) to query from the console, will get me 90% of the way there.

**Comment by jepiqueau** [comment]
@mjgoeke This is a bit tricky, usually you cannot really access the filesystem of a user inside the browser, but if it works you have what you want. I saw the same trick in an angular [](app https://stackblitz.com/edit/angular-file-save-as).
So i will close this. Thanks for using the plugin and the Stencil companion

**Comment by mjgoeke** [comment]
Thanks, one thing I notice, the db interface includes some web specific methods: `initWebStore()` and `saveToStore()`.
To export the db I had to pull in localForage separately and match the `name`, `storeName`, and key (`dbFilename`).
Could a method `exportWebStore()` that returns a `Promise<Uint8Array>` be added? (Feature request)
I think there's some nice symmetry in the 3 methods then, `initWebStore()` `saveToStore()` and `exportWebStore()`

I could add this as a feature request, to be tracked separately from this.
I could try to do the work and issue a PR if it'd help :-)

**Comment by jepiqueau** [comment]
@mjgoeke thanks for your proposal I think you should open a new issue and work from there. If you want to make a PR I do not have any problem. You should make one for jeep-sqlite, one for @capacitor-community/sqlite  and when I will accept I will update myself vue-sqlite-hook and react-sqlite-hook. Thanks for this proposal

**Comment by jepiqueau** [comment]
@mjgoeke I come back on you. With that method, what about the security issue? Any hackers can easily download quickly the databases stored by the browser

**Comment by mjgoeke** [comment]
I believe security comes from the browser only making indexedDb databases available to code running on site that “owns” the db.

That said, I don’t feel right expanding the shared interface either. I’m happy with my hacks methods to export for now.
Thanks!

For future viewers looking in the last comments for solutions, see the code block, a few comments up.

**Comment by khromov** [comment]
Thanks for this thread, for completeness, this is how you can *import* a file back into `jeep-sqlite`. 

First you need a form, something like this form:

```html
<h1>Import database</h1>
<div>
    <input type="file" id="file" name="file" />
    <button id="importDbBtn">Import Database</button>
</div>

<script>
    let fileInput = document.getElementById('file');

    const onImportDatabase = async () => {
        if(fileInput.files && fileInput.files.length > 0) {
            const dbFile = fileInput.files[0];
            await importDb(dbFile); 
        }
    }

    document.getElementById('importDbBtn').addEventListener('click', onImportDatabase);
</script>
```

And this import code:

```ts
import localForage from 'localforage';
export async function importDb(dbFile: File): Promise<void> {
	const reader = new FileReader();

	reader.onload = async (event) => {
		if (!event.target?.result) {
			console.log('❌ Could not read the file.');
			return;
		}

		// Convert result into Uint8Array format
		const data = new Uint8Array(event.target.result as ArrayBuffer);

		// Store the data in localForage
		const newDbInstance = localForage.createInstance({ name: 'jeepSqliteStore', storeName: 'databases' });
		await newDbInstance.setItem('dbnameSQLite.db', data);
	};

	reader.onerror = () => {
		console.log('❌ Error reading the file.');
	};

	reader.readAsArrayBuffer(dbFile);
};
```

Afterwards you probably want to reload the page just in case.

**Comment by pinguluk** [comment]
Hey everyone, I had the same issue and could not find an existing solution, so I built my own Chrome DevTools extension to inspect jeep-sqlite databases stored in IndexedDB.

Chrome Web Store:
[https://chromewebstore.google.com/detail/jeep-sqlite-browser/ocgeealadeabmhponndjebghfkbfbnch](https://chromewebstore.google.com/detail/jeep-sqlite-browser/ocgeealadeabmhponndjebghfkbfbnch)

GitHub:
[https://github.com/pinguluk/jeep-sqlite-browser](https://github.com/pinguluk/jeep-sqlite-browser)

Sharing it here in case it helps someone else running into this.
