### ISSUE TITLE
Show error log when calling saveToLocalDisk before open()

### ISSUE THREAD

**Issue by D-32** [jepiqueau/jeep-sqlite#37]
There's a error log when I call `saveToLocalDisk` before opening the connection, but if I call it before db.open() it just fails with `undefined`. Took me quite a long time to figure out it's because I was calling it too early. Could help others in the future.

**Comment by jepiqueau** [comment]
@D-32 fix in release 2.6.1

**Comment by D-32** [comment]
Thanks <3
