### ISSUE TITLE
Can't use getFromHTTPRequest for firebase storage

### ISSUE THREAD

**Issue by rosostolato** [jepiqueau/jeep-sqlite#39]
Firebase storage urls are of format: `${url}?alt=media&token=${token}`

To check if the file is db or zip, the script gets the full URL string and checks for the last chars without discarding the query params, causing the operation to be canceled.

https://github.com/jepiqueau/jeep-sqlite/blob/8176654951371fe5979061601b3164415c229fc5/src/components/jeep-sqlite/jeep-sqlite.tsx#L1650-L1657

**Comment by jepiqueau** [comment]
@rosostolato Fixed in 2.6.3. Please close the issue after successful tests

**Comment by rosostolato** [comment]
I couldn't make it work on some quick tests I did. I'm out of time now, so I just rolled back to version 2.6.2 and I'm adding an extra param to the end of the string with the extension format, just a workaround in the meantime. I will try again later and will bring some feedbacks.

`https://...?alt=media&token=...&ext=.zip`

**Comment by jepiqueau** [comment]
@rosostolato can you give me the url example for .db and .zip that you are using as for me it works

**Comment by rosostolato** [comment]
@jepiqueau sure!

https://firebasestorage.googleapis.com/v0/b/ipmacae-app.appspot.com/o/bibles%2FNVI.zip?alt=media&token=3c035e3e-7a5e-4532-bbf2-4e93e5d69b61

**Comment by jepiqueau** [comment]
@rosostolato fix in 2.6.4

**Comment by rosostolato** [comment]
Thank you!
