### ISSUE TITLE
Making jeep-sqlite vite-friendly

### ISSUE THREAD

**Issue by adamklein** [jepiqueau/jeep-sqlite#4]
Just wanted to raise awareness that 

https://github.com/ionic-team/stencil/issues/3118

affects me via jeep-sqlite, and the proposed PR 

https://github.com/ionic-team/stencil/pull/2959

seems to make progress toward a solution.

Otherwise thanks for all the great work!

**Comment by adamklein** [comment]
See, specifically, this comment: https://github.com/ionic-team/stencil/issues/2827#issuecomment-844335599

Maybe it's easy to incorporate in jeep-sqlite, I might give it a shot if I have a few moments

**Comment by jepiqueau** [comment]
@adamklein thanks for mentioning this. I do not really understand what is going on. Can you share the app or a small repro of the issue. Are you using `jeep-sqlite` in a Ionic/angular app with Capacitor? If you have time to find out a solution you can make a PR

**Comment by jepiqueau** [comment]
@adamklein I dig a bit i definitively needs that you share your app. `custom element` seems to be the solution provided by the Stencil team. So i will need to test it on a Vite app.

**Comment by jepiqueau** [comment]
@adamklein this is fixed in 1.3.2 see [https://github.com/jepiqueau/vuevite-app/blob/master/src/main.js](https://github.com/jepiqueau/vuevite-app/blob/master/src/main.js).

**Comment by jepiqueau** [comment]
@adamklein as I do not get any feedback I assume that it is working and then close the issue

**Comment by adamklein** [comment]
sorry I never wrote back. yes, this is fixed, thank you so much!!
