### ISSUE TITLE
Error: GetVersion: Memory access out of bounds

### ISSUE THREAD

**Issue by gymprogressive** [jepiqueau/jeep-sqlite#40]
Hello, can you tell me how to fix this error?

Error: GetVersion: Memory access out of bounds
      in _UtilsSQLite.getVersion (utils-sqlite.ts:99:29)

**Comment by jepiqueau** [comment]
@gymprogressive Can you give a bit more explanation on your context (use of jeep-sqlite in browser alone or with @capacitor-community/sqlite). Can you share your example as i cannot reproduce the error

**Comment by scope-li** [comment]
I have the same problem after upgrading from 2.6.3 to 2.7.2.

I get this in browser with @capacitor-community/sqlite 5.7.4 and douring SQLiteDBConnection.open() in a angular 17 project.

It's the same code, only update the dependencies.

**Comment by jepiqueau** [comment]
@scope-li can you give me a full example so i can test it easily and fix it

**Comment by scope-li** [comment]
@jepiqueau 

https://github.com/scope-li/reproducer-jeep-sqlite

Run it with `ng serve` and you will get the following error in brwoser on page (re)load:

```
Error: GetVersion: memory access out of bounds
    at _UtilsSQLite.<anonymous> (jeep-sqlite.entry.js:3899:35)
    at Generator.next (<anonymous>)
    at chunk-ATPMZF2Q.js?v=bc2d8fea:59:61
    at new ZoneAwarePromise (zone.js:2662:25)
    at __async (chunk-ATPMZF2Q.js?v=bc2d8fea:43:10)
    at _UtilsSQLite.getVersion (jeep-sqlite.entry.js:3883:33)
    at Database.<anonymous> (jeep-sqlite.entry.js:5577:56)
    at Generator.next (<anonymous>)
    at fulfilled (chunk-ATPMZF2Q.js?v=bc2d8fea:46:24)
    at _ZoneDelegate.invoke (zone.js:365:28)
```

**Comment by Yizack** [comment]
@scope-li 

I just ran your reproduction repo. To fix the issue, simply update the `src/assets/sql-wasm.wasm` file by replacing it with the version from `node_modules/sql.js/dist/sql-wasm.wasm` rebuild and that's all!

For every update from this package, always try this solution first.

![image](https://github.com/jepiqueau/jeep-sqlite/assets/16264115/ade2ca47-f657-4efe-9fed-cb16e76da359)

**Comment by scope-li** [comment]
Yes, thats solve the problem. Sorry, I forgot the replace of `sql-wasm.wasm`.
Thanks for your support!

**Comment by jepiqueau** [comment]
@Yizack @scope-li i am travelling, thanks to provide this advice which solves the issue
