### ISSUE TITLE
Webpack warning crypto

### ISSUE THREAD

**Issue by caiorsantanna** [jepiqueau/jeep-sqlite#44]
./node_modules/jeep-sqlite/dist/esm/jeep-sqlite.entry.js:2926:20-37 - Warning: Module not found: Error: Can't resolve 'crypto' in '/Volumes/Externo/Field/orc-3/node_modules/jeep-sqlite/dist/esm'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }

**Comment by wk-mihai** [comment]
As a temporary solution you can use this library https://www.npmjs.com/package/patch-package

1. Add the 'postinstall' script in your package.json file ["postinstall": "patch-package"]
2. Install the jeep-sqlite@2.5.4
3. npx patch-package jeep-sqlite
4. Commit the patches/jeep-sqlite+2.5.4.patch to your repo

Now every time you'll run _npm i_, the jeep-sqlite will be replaces with version 2.5.4

**Comment by jepiqueau** [comment]
@caiorsantanna @wk-mihai  the way to handle this is in your project

- with Vite: Put resolve.fallback: { crypto: false } in vite.config.ts or vite.config.js.
- with Webpack: Put resolve.fallback: { crypto: false } in webpack.config.js.

**Comment by jepiqueau** [comment]
@caiorsantanna @wk-mihai i close the issue feel free to re-open it if requires
