### ISSUE TITLE
jeep-sqlite can only instantiate from root folder

### ISSUE THREAD

**Issue by Lars-Sommer** [jepiqueau/jeep-sqlite#5]
I have a vuejs capacitor mobile application, and I´ve installed the capacitor-community/sqlite package along with jeep-sqlite. 
The sql-wasm.wasm file is located in the public\assets folder. 

When I run and serve the site, and opens http://localhost:8080/ in my browser, it works as expected. I can read and write to the database.
But I have several routes in my application, and when I use more than one path in the url, http://localhost:8080/a/b for an example, jeep-sql fails to load and throws this error:

Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -s ASSERTIONS=1 for more info.
    at K (jeep-sqlite.entry.js?e439:2590)
    at eval (jeep-sqlite.entry.js?e439:2650)

When googling this error, it typically has something to do with a wasm file not being loaded correctly. So it´s like the wasm file path is absolute, and not relative. 
Any clue?
Thanks!

**Comment by jepiqueau** [comment]
@fasterlars can you share how you instantanciate  the jeep-sqlite component or even better share your code so i could have a look

**Comment by Lars-Sommer** [comment]
Sure. I´ll try to pick out the relevant parts.

main.ts
```
import Vue from 'vue';
import App from './_ui/_layouts/App.vue';
import router from './system/router';
import vuetify from './system/plugins/vuetify';
import 'sql.js';
import 'reflect-metadata';

import { defineCustomElements as jeepSqlite, applyPolyfills } from 'jeep-sqlite/loader';
applyPolyfills().then(() => {
	jeepSqlite(window);
});
```


sqlDB.ts

	```
	
	async init() {
		const platform = Capacitor.getPlatform();

		if (platform === 'web') {
			const jeepSqliteEl = document.createElement('jeep-sqlite');
			document.body.appendChild(jeepSqliteEl);
			await customElements.whenDefined('jeep-sqlite');

			if (jeepSqliteEl != null) {
				// Initialize the Web Store since @capacitor-community/sqlite@3.2.3-1
				await this._sqlite.initWebStore();

				console.log(`isStoreOpen ${await jeepSqliteEl.isStoreOpen()}`);
			}
		}

		const hello = await this.sqlite.echo('Sql established');
		if (hello.value) {
			console.log(hello.value);
		} else {
			console.error('Database connection failed!');
		}

		await this.connect();
	}	
	
	async connect() {
		console.log('Connecting DB: ' + this.DATABASE_NAME);

		try {
			this.connection = await createConnection({
				type: 'capacitor',
				database: this.DATABASE_NAME,
				driver: new SQLiteConnection(CapacitorSQLite),
				mode: 'no-encryption',
				entities: [Location, Device]
			});
			console.log('Connection successfull');
		} catch (error) {
			console.error('Error in createConnection: ' + error);
		}
	}


	
Refresh on http://localhost:8080/	
![image](https://user-images.githubusercontent.com/42839536/146722884-ed6261b6-df18-4cd3-bc78-d3caf51c3d2b.png)

Refresh on http://localhost:8080/a/b	
![image](https://user-images.githubusercontent.com/42839536/146722983-9e93d059-ca75-42c1-9932-809b9ec8f0a8.png)

Packages:
	        "@capacitor/android": "^3.2.3",
		"@capacitor/app": "^1.0.3",	
		"@capacitor/ios": "^3.2.4",
		"@capacitor/network": "^1.0.3",	
		"reflect-metadata": "^0.1.13",
		"swiper": "^6.5.1",
		"typeorm": "^0.2.41",		
		"vue": "^2.6.11",	
		"vue-router": "^3.2.0",
		"vue-sqlite-hook": "^2.1.4",

Dev packages:
                "@capacitor-community/sqlite": "^3.3.1",
		"@capacitor/cli": "^3.2.3",		
		"jeep-sqlite": "^1.3.1",		
		

Thanks!

**Comment by jepiqueau** [comment]
@fasterlars it has to be done in the `main.ts` look at `https://github.com/jepiqueau/vue-typeorm-app` to help you starting

**Comment by Lars-Sommer** [comment]
Thanks, I´ll look into it 👍

**Comment by jepiqueau** [comment]
@fasterlars After having try a lot of things with another developer that the only way we found to make it working with vue at that time. Good luck.

**Comment by jepiqueau** [comment]
@fasterlars Did you finally make your app working? If yes and you are happy can you please close the issue

**Comment by Lars-Sommer** [comment]
Not yot, but I have confirmed that your example app works with nested routes, so it has to be a problem in my setup.
Thanks!

**Comment by jepiqueau** [comment]
@fasterlars can you tell me which is the Node version you are using?

**Comment by Lars-Sommer** [comment]
My node version is 14.15.0

**Comment by jepiqueau** [comment]
@fasterlars OK thanks

**Comment by Chris2011** [comment]
I also had this problem and the solution for this is to set the base path in `/public/index.html` as you can see here: https://github.com/jepiqueau/vue-typeorm-app/blob/main/public/index.html#L7

**Comment by jepiqueau** [comment]
@Chris2011 Thanks for this comment, i forgot that i need to add that in the [https://github.com/jepiqueau/vue-typeorm-app](https://github.com/jepiqueau/vue-typeorm-app). @fasterlars Hope this will help you

**Comment by Lars-Sommer** [comment]
Ah ok! I will look into it, thanks 👍
