### ISSUE TITLE
Negative ID's not allowed

### ISSUE THREAD

**Issue by muuvmuuv** [jepiqueau/jeep-sqlite#7]
Negative ID's are allowed to use in SQLite and we use them quite often, can you remove that line that throws or why was that if-clause added? I thinks this checks is used very often so other parts might also need a change. Removing the lines throws no DB error.

https://github.com/jepiqueau/jeep-sqlite/blob/master/src/utils/database.ts#L210-L212

> node_modules/jeep-sqlite/dist/esm/jeep-sqlite.entry.js:4778~4781

**Comment by jepiqueau** [comment]
@muuvmuuv Using Negative ID's are a bad practice in SQLite and i returned -1 when there is an error so this will have a big impact not only on `jeep-sqlite` but also on the `@capacitor-community/sqlite` so i will not go that way sorry for this.

**Comment by muuvmuuv** [comment]
Can you elaborate more why this is bad practise? I see from searching that this is a common pattern. Unfortunately, we need to patch each release due to our app using negative ids in cordova-sqlite before. I would love to change that on our side but the team decided to not migrate our negative ids due to using it since 2017 in our app without issues ^^.

**Comment by jepiqueau** [comment]
@muuvmuuv you can Google for sqlite and negative ids which is what i did. Now i will try to evaluate the work implies.

**Comment by muuvmuuv** [comment]
Okay thanks, I searched that before but couldn't find any "bad-practise" example so thought its just a design decission. I put it on the schedule for the next team meeting to talk about the situation internally.

**Comment by jepiqueau** [comment]
@muuvmuuv i think there is also a confusion the lastId returned is the SQLite rowId so this one could not be negative so this is not YOUR_TABLE ID. to get YOUR_TABLE ID from lastId you must do `SELECT ID from table where rowid=lastId`

**Comment by muuvmuuv** [comment]
I was referring to the row id. What we are doing is sending "fake rows" to the client (dont ask me whoever came up with that idea) and those get a negative id to not collide with the ones in the db. Anyway we figured out that it just works to use the highest row id and +1 them for these fake rows. So, we will go that way. Sometimes its good when someone tells one bad-practises to follow conventions haha thanks for pointing that out! Your plugins work great with our new release and all migrations ran super smooth!

**Comment by jepiqueau** [comment]
@muuvmuuv i am quitte happy of this. Couleur Lucky with your development

**Comment by jepiqueau** [comment]
@muuvmuuv i mean good luck with your development
