### ISSUE TITLE
Option to disable logging

### ISSUE THREAD

**Issue by muuvmuuv** [jepiqueau/jeep-sqlite#8]
In production, it does not make any real sense to print the store name to the console, and it infers with our way of handling console events. It is also included in our Sentry logs. 

I also see no real cause why this is printed to the console. The fallback name is known, and any other store name defined by the dev. It is a once set and forget var. I suggest removing it entirely and also remove the `>>>` in the exception to make them more generic. Dev's should take care of the styling of their logs themselves, IMO.

PS: using the lib in prod now for two weeks, thanks for the work, it is working great!

**Comment by jepiqueau** [comment]
@muuvmuuv yes you right i will remove it

**Comment by jepiqueau** [comment]
@muuvmuuv this has been fixed in release 1.3.5
